[terminal]
shell = {
	program = "pwsh -NoLogo",
	#args = "-NoLogo"
}

[general]
import = [
	"themes/themes/gruvbox_dark.toml",
]
live_config_reload = true

[window]
padding = { x=4,y=4 }
dynamic_padding = true
decorations = "Full"

[font]
size = 12.0
normal = { family = "JetBrainsMono NF", style = "Regular" }

[cursor]
vi_mode_style = { shape = "Underline",  blinking = "On" }

[mouse]
hide_when_typing = true

