watch_stylesheet: true
watch_config: true
debug: false
update_check: true # Enable automatic update check.
bars:
  status-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: true
      dark_mode: false
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 24
    padding:
      top: 2
      left: 2
      bottom: 0
      right: 2
    widgets:
      left:
        - "power_menu"
        - "memory"
        - "active_window"
      center:
        - "glazewm_workspaces"
      right:
        - "notifications"
        - "media"
        - "volume"
        - "clock"
        - "weather"
widgets:
  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 12
      framerate: 120
      sleep_timer: 60
      hide_empty: true
      gradient: 0
      foreground: "#e2cca9"
      container_padding:
        top: 3
        right: 2
        bottom: 3
        left: 3
  media:
   type: "yasb.media.MediaWidget"
   options:
     label: "<span>\uf001</span> {title}"
     label_alt: "<span>\uf001</span> {artist} - {title}"
     max_field_size:
       label: 32
       label_alt:  32
     hide_empty: true
     show_thumbnail: true
     controls_hide: true
     thumbnail_alpha: 50
     thumbnail_padding: 20
     thumbnail_corner_radius: 5
     icons:
       prev_track: "\uf04ae"
       next_track: "\uf04ad"
       play: "\uf040a"
       pause: "\uf03e4"
     media_menu_icons:
       prev_track: "\udb81\udcae"
       next_track: "\udb81\udcad"
       play: "\udb81\udc0a"
       pause: "\udb80\udfe4"
     callbacks:
       on_left: "toggle_media_menu"
     #  on_left: "do_nothing"

  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf476</span> {count}"
      label_alt: "{count} notifications"
      hide_empty: true
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "do_nothing"
        on_middle: "toggle_label"

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>{icon}</span> {%H:%M} <span>\uf133</span> {%m/%d/%Y}"
      timezones: [] #Looking up time zone info from registry
      icons:
        clock_00: "\ue32b"
        clock_01: "\ue32b"
        clock_02: "\ue32b"
        clock_03: "\ue3c2"
        clock_04: "\ue3c2"
        clock_05: "\ue3c2"
        clock_06: "\ue34c"
        clock_07: "\ue34c"
        clock_08: "\ue34c"
        clock_09: "\ue343"
        clock_10: "\ue343"
        clock_11: "\ue30d"
        clock_12: "\ue30d"
        clock_13: "\ue30d"
        clock_14: "\ue343"
        clock_15: "\ue343"
        clock_16: "\ue34d"
        clock_17: "\ue34d"
        clock_18: "\ue34d"
        clock_19: "\ue3c1"
        clock_20: "\ue3c1"
        clock_21: "\ue3c1"
        clock_22: "\ue32b"
        clock_23: "\ue32b"
      calendar:
        alignment: "center"
      callbacks:
        on_left: "toggle_calendar"
        on_right: "do_nothing"
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 16
      animation: true
      ignore_apps:
        processes: []
        titles: []
        classes: []
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "\u26a1 Offline"
      hide_empty_workspaces: false
      hide_if_offline: true
      animation: false
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      api_key: "3bf4cf9a7c3f40d6b31174128242807"
      update_interval: 600
      units: "imperial"
      hide_decimal: true
      location: "USA Flowood 39232"
      show_alerts: true
      weather_card:
        alignment: "center"
        offset_left: 150
      callbacks:
        on_left: "toggle_card"
      icons:
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\ue311"
        rainyDay: "\udb81\ude7e"
        rainyNight: "\udb81\ude7e"
        snowyDay: "\udb81\udd98"
        snowyNight: "\udb81\udd98"
        blizzardDay: "\uebaa"
        default: "\uebaa"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueb24" # Icon for muted
        - "\uf026" # Icon for 0-10% volume
        - "\uf027" # Icon for 11-30% volume
        - "\uf027" # Icon for 31-60% volume
        - "\uf028" # Icon for 61-100% volume
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"
        on_middle: "toggle_mute"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: False
      blur: False
      blur_background: True
      animation_duration: 100 # Milisecond
      button_row: 4 # Number of buttons in row, min 1 max 5
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[process][name]}"
      label_alt: ""
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 40
      max_length_ellipsis: "..."
      monitor_exclusive: false
      callbacks:
        on_left: "do_nothing"
  language:
    type: "yasb.language.LanguageWidget"
    options:
      label: "<span>\uf11c</span> {lang[language_code]}"
      label_alt: "{lang[full_name]}"
      update_interval: 1
      callbacks:
        on_left: "do_nothing"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      container_padding:
        bottom: 1
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uf4bc</span> {virtual_mem_percent}%"
      #label_alt: "<span>\uf4bc</span> VIRT: {virtual_mem_percent}% SWAP: {swap_mem_percent}%"
      update_interval: 10000
      hide_decimal: true
      callbacks:
        on_left: "toggle_label"
        on_right: "toggle_menu"
      memory_thresholds:
        low: 25
        medium: 50
        high: 90
      histogram_icons:
        - "\u2581" # 0%
        - "\u2581" # 10%
        - "\u2582" # 20%
        - "\u2583" # 30%
        - "\u2584" # 40%
        - "\u2585" # 50%
        - "\u2586" # 60%
        - "\u2587" # 70%
        - "\u2588" # 80%+
